module.exports = [
{ set: "10E", setName: "Tenth Edition"},
{ set: "2ED", setName: "Unlimited Edition"},
{ set: "3ED", setName: "Revised Edition"},
{ set: "4ED", setName: "Fourth Edition"},
{ set: "5DN", setName: "Fifth Dawn"},
{ set: "5ED", setName: "Fifth Edition"},
{ set: "6ED", setName: "Classic Sixth Edition"},
{ set: "7ED", setName: "Seventh Edition"},
{ set: "8ED", setName: "Eighth Edition"},
{ set: "9ED", setName: "Ninth Edition"},
{ set: "A25", setName: "Masters 25"},
{ set: "AER", setName: "Aether Revolt"},
{ set: "AKH", setName: "Amonkhet"},
{ set: "ALA", setName: "Shards of Alara"},
{ set: "ALL", setName: "Alliances"},
{ set: "ANA", setName: "Arena New Player Experience"},
{ set: "APC", setName: "Apocalypse"},
{ set: "ARB", setName: "Alara Reborn"},
{ set: "ARC", setName: "Archenemy"},
{ set: "ARN", setName: "Arabian Nights"},
{ set: "ATH", setName: "Anthologies"},
{ set: "ATQ", setName: "Antiquities"},
{ set: "AVR", setName: "Avacyn Restored"},
{ set: "DDD", setName: "Duel Decks: Garruk vs. Liliana"},
{ set: "BBD", setName: "Battlebond"},
{ set: "BFZ", setName: "Battle for Zendikar"},
{ set: "BNG", setName: "Born of the Gods"},
{ set: "BOK", setName: "Betrayers of Kamigawa"},
{ set: "BRB", setName: "Battle Royale Box Set"},
{ set: "BTD", setName: "Beatdown Box Set"},
{ set: "C13", setName: "Commander 2013"},
{ set: "C14", setName: "Commander 2014"},
{ set: "C15", setName: "Commander 2015"},
{ set: "C16", setName: "Commander 2016"},
{ set: "C17", setName: "Commander 2017"},
{ set: "C18", setName: "Commander 2018"},
{ set: "CED", setName: "Collectors’ Edition"},
{ set: "CEI", setName: "Intl. Collectors’ Edition"},
{ set: "CHK", setName: "Champions of Kamigawa"},
{ set: "CHR", setName: "Chronicles"},
{ set: "CM1", setName: "Commander's Arsenal"},
{ set: "CM2", setName: "Commander Anthology Volume II"},
{ set: "CMA", setName: "Commander Anthology"},
{ set: "CMD", setName: "Commander 2011"},
{ set: "CN2", setName: "Conspiracy: Take the Crown"},
{ set: "CNS", setName: "Conspiracy"},
{ set: "CON", setName: "Conflux"},
{ set: "CP1", setName: "Magic 2015 Clash Pack"},
{ set: "CP2", setName: "Fate Reforged Clash Pack"},
{ set: "CP3", setName: "Magic Origins Clash Pack"},
{ set: "CSP", setName: "Coldsnap"},
{ set: "CST", setName: "Coldsnap Theme Decks"},
{ set: "DD1", setName: "Duel Decks: Elves vs. Goblins"},
{ set: "DD2", setName: "Duel Decks: Jace vs. Chandra"},
{ set: "DDC", setName: "Duel Decks: Divine vs. Demonic"},
{ set: "DDE", setName: "Duel Decks: Phyrexia vs. the Coalition"},
{ set: "DDF", setName: "Duel Decks: Elspeth vs. Tezzeret"},
{ set: "DDG", setName: "Duel Decks: Knights vs. Dragons"},
{ set: "DDH", setName: "Duel Decks: Ajani vs. Nicol Bolas"},
{ set: "DDI", setName: "Duel Decks: Venser vs. Koth"},
{ set: "DDJ", setName: "Duel Decks: Izzet vs. Golgari"},
{ set: "DDK", setName: "Duel Decks: Sorin vs. Tibalt"},
{ set: "DDL", setName: "Duel Decks: Heroes vs. Monsters"},
{ set: "DDM", setName: "Duel Decks: Jace vs. Vraska"},
{ set: "DDN", setName: "Duel Decks: Speed vs. Cunning"},
{ set: "DDO", setName: "Duel Decks: Elspeth vs. Kiora"},
{ set: "DDP", setName: "Duel Decks: Zendikar vs. Eldrazi"},
{ set: "DDQ", setName: "Duel Decks: Blessed vs. Cursed"},
{ set: "DDR", setName: "Duel Decks: Nissa vs. Ob Nixilis"},
{ set: "DDS", setName: "Duel Decks: Mind vs. Might"},
{ set: "DDT", setName: "Duel Decks: Merfolk vs. Goblins"},
{ set: "DDU", setName: "Duel Decks: Elves vs. Inventors"},
{ set: "DGM", setName: "Dragon's Maze"},
{ set: "DIS", setName: "Dissension"},
{ set: "DKA", setName: "Dark Ascension"},
{ set: "DKM", setName: "Deckmasters"},
{ set: "DOM", setName: "Dominaria"},
{ set: "DPA", setName: "Duels of the Planeswalkers"},
{ set: "DRB", setName: "From the Vault: Dragons"},
{ set: "DRK", setName: "The Dark"},
{ set: "DST", setName: "Darksteel"},
{ set: "DTK", setName: "Dragons of Tarkir"},
{ set: "DVD", setName: "Duel Decks Anthology: Divine vs. Demonic"},
{ set: "E01", setName: "Archenemy: Nicol Bolas"},
{ set: "E02", setName: "Explorers of Ixalan"},
{ set: "EMA", setName: "Eternal Masters"},
{ set: "G03", setName: "Judge Gift Cards 2003"},
{ set: "EMN", setName: "Eldritch Moon"},
{ set: "EVE", setName: "Eventide"},
{ set: "EVG", setName: "Duel Decks Anthology: Elves vs. Goblins"},
{ set: "EXO", setName: "Exodus"},
{ set: "EXP", setName: "Zendikar Expeditions"},
{ set: "F01", setName: "Friday Night Magic 2001"},
{ set: "F02", setName: "Friday Night Magic 2002"},
{ set: "F03", setName: "Friday Night Magic 2003"},
{ set: "F04", setName: "Friday Night Magic 2004"},
{ set: "F05", setName: "Friday Night Magic 2005"},
{ set: "F06", setName: "Friday Night Magic 2006"},
{ set: "F07", setName: "Friday Night Magic 2007"},
{ set: "F08", setName: "Friday Night Magic 2008"},
{ set: "F09", setName: "Friday Night Magic 2009"},
{ set: "F10", setName: "Friday Night Magic 2010"},
{ set: "F11", setName: "Friday Night Magic 2011"},
{ set: "F12", setName: "Friday Night Magic 2012"},
{ set: "F13", setName: "Friday Night Magic 2013"},
{ set: "F14", setName: "Friday Night Magic 2014"},
{ set: "F15", setName: "Friday Night Magic 2015"},
{ set: "F16", setName: "Friday Night Magic 2016"},
{ set: "F17", setName: "Friday Night Magic 2017"},
{ set: "FBB", setName: "Foreign Black Border"},
{ set: "FEM", setName: "Fallen Empires"},
{ set: "FNM", setName: "Friday Night Magic 2000"},
{ set: "FRF", setName: "Fate Reforged"},
{ set: "FUT", setName: "Future Sight"},
{ set: "G00", setName: "Judge Gift Cards 2000"},
{ set: "G01", setName: "Judge Gift Cards 2001"},
{ set: "G02", setName: "Judge Gift Cards 2002"},
{ set: "G04", setName: "Judge Gift Cards 2004"},
{ set: "G05", setName: "Judge Gift Cards 2005"},
{ set: "G06", setName: "Judge Gift Cards 2006"},
{ set: "G07", setName: "Judge Gift Cards 2007"},
{ set: "G08", setName: "Judge Gift Cards 2008"},
{ set: "G09", setName: "Judge Gift Cards 2009"},
{ set: "G10", setName: "Judge Gift Cards 2010"},
{ set: "G11", setName: "Judge Gift Cards 2011"},
{ set: "G99", setName: "Judge Gift Cards 1999"},
{ set: "GK1", setName: "GRN Guild Kit"},
{ set: "GK2", setName: "RNA Guild Kit"},
{ set: "GNT", setName: "Game Night"},
{ set: "GPT", setName: "Guildpact"},
{ set: "GRN", setName: "Guilds of Ravnica"},
{ set: "GS1", setName: "Global Series Jiang Yanggu & Mu Yanling"},
{ set: "GTC", setName: "Gatecrash"},
{ set: "GVL", setName: "Duel Decks Anthology: Garruk vs. Liliana"},
{ set: "H09", setName: "Premium Deck Series: Slivers"},
{ set: "H17", setName: "HasCon 2017"},
{ set: "HHO", setName: "Happy Holidays"},
{ set: "HML", setName: "Homelands"},
{ set: "HOP", setName: "Planechase"},
{ set: "HOU", setName: "Hour of Devastation"},
{ set: "HTR", setName: "2016 Heroes of the Realm"},
{ set: "HTR17", setName: "2017 Heroes of the Realm"},
{ set: "ICE", setName: "Ice Age"},
{ set: "IMA", setName: "Iconic Masters"},
{ set: "INV", setName: "Invasion"},
{ set: "ISD", setName: "Innistrad"},
{ set: "ITP", setName: "Introductory Two-Player Set"},
{ set: "J12", setName: "Judge Gift Cards 2012"},
{ set: "J13", setName: "Judge Gift Cards 2013"},
{ set: "J14", setName: "Judge Gift Cards 2014"},
{ set: "J15", setName: "Judge Gift Cards 2015"},
{ set: "J16", setName: "Judge Gift Cards 2016"},
{ set: "J17", setName: "Judge Gift Cards 2017"},
{ set: "J18", setName: "Judge Gift Cards 2018"},
{ set: "JGP", setName: "Judge Gift Cards 1998"},
{ set: "JOU", setName: "Journey into Nyx"},
{ set: "JUD", setName: "Judgment"},
{ set: "JVC", setName: "Duel Decks Anthology: Jace vs. Chandra"},
{ set: "KLD", setName: "Kaladesh"},
{ set: "KTK", setName: "Khans of Tarkir"},
{ set: "L12", setName: "League Tokens 2012"},
{ set: "L13", setName: "League Tokens 2013"},
{ set: "L14", setName: "League Tokens 2014"},
{ set: "L15", setName: "League Tokens 2015"},
{ set: "LEA", setName: "Limited Edition Alpha"},
{ set: "LEB", setName: "Limited Edition Beta"},
{ set: "LEG", setName: "Legends"},
{ set: "LGN", setName: "Legions"},
{ set: "LRW", setName: "Lorwyn"},
{ set: "M10", setName: "Magic 2010"},
{ set: "M11", setName: "Magic 2011"},
{ set: "M12", setName: "Magic 2012"},
{ set: "M13", setName: "Magic 2013"},
{ set: "M14", setName: "Magic 2014"},
{ set: "M15", setName: "Magic 2015"},
{ set: "M19", setName: "Core Set 2019"},
{ set: "MBS", setName: "Mirrodin Besieged"},
{ set: "MD1", setName: "Modern Event Deck 2014"},
{ set: "ME1", setName: "Masters Edition"},
{ set: "ME2", setName: "Masters Edition II"},
{ set: "ME3", setName: "Masters Edition III"},
{ set: "ME4", setName: "Masters Edition IV"},
{ set: "MED", setName: "Mythic Edition"},
{ set: "MGB", setName: "Multiverse Gift Box"},
{ set: "MIR", setName: "Mirage"},
{ set: "MM2", setName: "Modern Masters 2015"},
{ set: "MM3", setName: "Modern Masters 2017"},
{ set: "MMA", setName: "Modern Masters"},
{ set: "MMQ", setName: "Mercadian Masques"},
{ set: "MOR", setName: "Morningtide"},
{ set: "MP2", setName: "Amonkhet Invocations"},
{ set: "MPR", setName: "Magic Player Rewards 2001"},
{ set: "MPS", setName: "Kaladesh Inventions"},
{ set: "MRD", setName: "Mirrodin"},
{ set: "NEM", setName: "Nemesis"},
{ set: "NPH", setName: "New Phyrexia"},
{ set: "OC13", setName: "Commander 2013 Oversized"},
{ set: "OC14", setName: "Commander 2014 Oversized"},
{ set: "OC15", setName: "Commander 2015 Oversized"},
{ set: "OC16", setName: "Commander 2016 Oversized"},
{ set: "OC17", setName: "Commander 2017 Oversized"},
{ set: "OC18", setName: "Commander 2018 Oversized"},
{ set: "OCM1", setName: "Commander's Arsenal Oversized"},
{ set: "OCMD", setName: "Commander 2011 Oversized"},
{ set: "ODY", setName: "Odyssey"},
{ set: "OGW", setName: "Oath of the Gatewatch"},
{ set: "OLGC", setName: "Legacy Championship"},
{ set: "ONS", setName: "Onslaught"},
{ set: "ORI", setName: "Magic Origins"},
{ set: "OVNT", setName: "Vintage Championship"},
{ set: "P02", setName: "Portal Second Age"},
{ set: "P03", setName: "Magic Player Rewards 2003"},
{ set: "P04", setName: "Magic Player Rewards 2004"},
{ set: "P05", setName: "Magic Player Rewards 2005"},
{ set: "P06", setName: "Magic Player Rewards 2006"},
{ set: "P07", setName: "Magic Player Rewards 2007"},
{ set: "P08", setName: "Magic Player Rewards 2008"},
{ set: "P09", setName: "Magic Player Rewards 2009"},
{ set: "P10", setName: "Magic Player Rewards 2010"},
{ set: "P10E", setName: "Tenth Edition Promos"},
{ set: "P11", setName: "Magic Player Rewards 2011"},
{ set: "P15A", setName: "15th Anniversary Cards"},
{ set: "P2HG", setName: "Two-Headed Giant Tournament"},
{ set: "PAER", setName: "Aether Revolt Promos"},
{ set: "PAKH", setName: "Amonkhet Promos"},
{ set: "PAL00", setName: "Arena League 2000"},
{ set: "PAL01", setName: "Arena League 2001"},
{ set: "PAL02", setName: "Arena League 2002"},
{ set: "PAL03", setName: "Arena League 2003"},
{ set: "PAL04", setName: "Arena League 2004"},
{ set: "PAL05", setName: "Arena League 2005"},
{ set: "PAL06", setName: "Arena League 2006"},
{ set: "PAL99", setName: "Arena League 1999"},
{ set: "PALP", setName: "Asia Pacific Land Program"},
{ set: "PARC", setName: "Promotional Schemes"},
{ set: "PARL", setName: "Arena League 1996"},
{ set: "PAVR", setName: "Avacyn Restored Promos"},
{ set: "PBBD", setName: "Battlebond Promos"},
{ set: "PBFZ", setName: "Battle for Zendikar Promos"},
{ set: "PBNG", setName: "Born of the Gods Promos"},
{ set: "PBOK", setName: "Miscellaneous Book Promos"},
{ set: "PC2", setName: "Planechase 2012"},
{ set: "PCA", setName: "Planechase Anthology"},
{ set: "PCEL", setName: "Celebration Cards"},
{ set: "PCMD", setName: "Commander 2011 Launch Party"},
{ set: "PCMP", setName: "Champs and States"},
{ set: "PCY", setName: "Prophecy"},
{ set: "PD2", setName: "Premium Deck Series: Fire and Lightning"},
{ set: "PD3", setName: "Premium Deck Series: Graveborn"},
{ set: "PDD2", setName: "Duel Decks: Jace vs. Chandra Japanese Promos"},
{ set: "PDGM", setName: "Dragon's Maze Promos"},
{ set: "PDKA", setName: "Dark Ascension Promos"},
{ set: "PDOM", setName: "Dominaria Promos"},
{ set: "PDP10", setName: "Duels of the Planeswalkers Promos 2010"},
{ set: "PDP11", setName: "Duels of the Planeswalkers Promos 2011"},
{ set: "PDP12", setName: "Duels of the Planeswalkers Promos 2012"},
{ set: "PDP13", setName: "Duels of the Planeswalkers Promos 2013"},
{ set: "PDP14", setName: "Duels of the Planeswalkers Promos 2014"},
{ set: "PDRC", setName: "Dragon Con"},
{ set: "PDTK", setName: "Dragons of Tarkir Promos"},
{ set: "PDTP", setName: "Duels of the Planeswalkers Promos 2009"},
{ set: "PELP", setName: "European Land Program"},
{ set: "PEMN", setName: "Eldritch Moon Promos"},
{ set: "PF19", setName: "Magic Fest 2019"},
{ set: "PFRF", setName: "Fate Reforged Promos"},
{ set: "PG07", setName: "Gateway 2007"},
{ set: "PG08", setName: "Gateway 2008"},
{ set: "PGP1", setName: "M19 Gift Pack"},
{ set: "PGP17", setName: "2017 Gift Pack"},
{ set: "PGPX", setName: "Grand Prix Promos"},
{ set: "PGRN", setName: "Guilds of Ravnica Promos"},
{ set: "PGRU", setName: "Guru"},
{ set: "PGTC", setName: "Gatecrash Promos"},
{ set: "PGTW", setName: "Gateway 2006"},
{ set: "PHEL", setName: "Open the Helvault"},
{ set: "PHOP", setName: "Promotional Planes"},
{ set: "PHOU", setName: "Hour of Devastation Promos"},
{ set: "PHPR", setName: "HarperPrism Book Promos"},
{ set: "PHUK", setName: "Hachette UK"},
{ set: "PI13", setName: "IDW Comics 2013"},
{ set: "PI14", setName: "IDW Comics 2014"},
{ set: "PIDW", setName: "IDW Comics 2012"},
{ set: "PISD", setName: "Innistrad Promos"},
{ set: "PJAS", setName: "Junior APAC Series"},
{ set: "PJJT", setName: "Japan Junior Tournament"},
{ set: "PJOU", setName: "Journey into Nyx Promos"},
{ set: "PJSE", setName: "Junior Series Europe"},
{ set: "PKLD", setName: "Kaladesh Promos"},
{ set: "PKTK", setName: "Khans of Tarkir Promos"},
{ set: "PLC", setName: "Planar Chaos"},
{ set: "PLGM", setName: "DCI Legend Membership"},
{ set: "PLNY", setName: "2018 Lunar New Year"},
{ set: "PLPA", setName: "Launch Parties"},
{ set: "PLS", setName: "Planeshift"},
{ set: "PM10", setName: "Magic 2010 Promos"},
{ set: "PM11", setName: "Magic 2011 Promos"},
{ set: "PM12", setName: "Magic 2012 Promos"},
{ set: "PM13", setName: "Magic 2013 Promos"},
{ set: "PM14", setName: "Magic 2014 Promos"},
{ set: "PM15", setName: "Magic 2015 Promos"},
{ set: "PM19", setName: "Core Set 2019 Promos"},
{ set: "PMBS", setName: "Mirrodin Besieged Promos"},
{ set: "PMEI", setName: "Magazine Inserts"},
{ set: "PMOA", setName: "Magic Online Avatars"},
{ set: "PMPS", setName: "Magic Premiere Shop 2005"},
{ set: "PMPS06", setName: "Magic Premiere Shop 2006"},
{ set: "PMPS07", setName: "Magic Premiere Shop 2007"},
{ set: "PMPS08", setName: "Magic Premiere Shop 2008"},
{ set: "PMPS09", setName: "Magic Premiere Shop 2009"},
{ set: "PMPS10", setName: "Magic Premiere Shop 2010"},
{ set: "PMPS11", setName: "Magic Premiere Shop 2011"},
{ set: "PNAT", setName: "Nationals Promos"},
{ set: "PNPH", setName: "New Phyrexia Promos"},
{ set: "POGW", setName: "Oath of the Gatewatch Promos"},
{ set: "POR", setName: "Portal"},
{ set: "PORI", setName: "Magic Origins Promos"},
{ set: "PPC1", setName: "M15 Prerelease Challenge"},
{ set: "PPOD", setName: "Portal Demo Game"},
{ set: "PPRE", setName: "Prerelease Events"},
{ set: "PPRO", setName: "Pro Tour Promos"},
{ set: "PR2", setName: "Magic Player Rewards 2002"},
{ set: "PREL", setName: "Release Events"},
{ set: "PRES", setName: "Resale Promos"},
{ set: "PRIX", setName: "Rivals of Ixalan Promos"},
{ set: "PRM", setName: "Magic Online Promos"},
{ set: "PRNA", setName: "Ravnica Allegiance Promos"},
{ set: "PROE", setName: "Rise of the Eldrazi Promos"},
{ set: "PRTR", setName: "Return to Ravnica Promos"},
{ set: "PRW2", setName: "RNA Ravnica Weekend"},
{ set: "PRWK", setName: "GRN Ravnica Weekend"},
{ set: "PS11", setName: "Salvat 2011"},
{ set: "PS14", setName: "San Diego Comic-Con 2014"},
{ set: "PS15", setName: "San Diego Comic-Con 2015"},
{ set: "PS16", setName: "San Diego Comic-Con 2016"},
{ set: "PS17", setName: "San Diego Comic-Con 2017"},
{ set: "PS18", setName: "San Diego Comic-Con 2018"},
{ set: "PSAL", setName: "Salvat 2005"},
{ set: "PSDC", setName: "San Diego Comic-Con 2013"},
{ set: "PSOI", setName: "Shadows over Innistrad Promos"},
{ set: "PSOM", setName: "Scars of Mirrodin Promos"},
{ set: "PSS1", setName: "BFZ Standard Series"},
{ set: "PSS2", setName: "XLN Standard Showdown"},
{ set: "PSS3", setName: "M19 Standard Showdown"},
{ set: "PSUM", setName: "Summer of Magic"},
{ set: "PSUS", setName: "Junior Super Series"},
{ set: "PTC", setName: "Pro Tour Collector Set"},
{ set: "PTHS", setName: "Theros Promos"},
{ set: "PTK", setName: "Portal Three Kingdoms"},
{ set: "PTKDF", setName: "Tarkir Dragonfury"},
{ set: "PUMA", setName: "Ultimate Box Topper"},
{ set: "PURL", setName: "URL/Convention Promos"},
{ set: "PUST", setName: "Unstable Promos"},
{ set: "PVAN", setName: "Vanguard Series"},
{ set: "PWCQ", setName: "World Magic Cup Qualifiers"},
{ set: "PWOR", setName: "Worlds"},
{ set: "PWOS", setName: "Wizards of the Coast Online Store"},
{ set: "PWP09", setName: "Wizards Play Network 2009"},
{ set: "PWP10", setName: "Wizards Play Network 2010"},
{ set: "PWP11", setName: "Wizards Play Network 2011"},
{ set: "PWP12", setName: "Wizards Play Network 2012"},
{ set: "PWPN", setName: "Wizards Play Network 2008"},
{ set: "PWWK", setName: "Worldwake Promos"},
{ set: "PXLN", setName: "Ixalan Promos"},
{ set: "PXTC", setName: "XLN Treasure Chest"},
{ set: "PZ1", setName: "Legendary Cube"},
{ set: "PZ2", setName: "You Make the Cube"},
{ set: "PZEN", setName: "Zendikar Promos"},
{ set: "RAV", setName: "Ravnica: City of Guilds"},
{ set: "REN", setName: "Renaissance"},
{ set: "RIN", setName: "Rinascimento"},
{ set: "RIX", setName: "Rivals of Ixalan"},
{ set: "RNA", setName: "Ravnica Allegiance"},
{ set: "ROE", setName: "Rise of the Eldrazi"},
{ set: "RQS", setName: "Rivals Quick Start Set"},
{ set: "RTR", setName: "Return to Ravnica"},
{ set: "S00", setName: "Starter 2000"},
{ set: "S99", setName: "Starter 1999"},
{ set: "SCG", setName: "Scourge"},
{ set: "SHM", setName: "Shadowmoor"},
{ set: "SOI", setName: "Shadows over Innistrad"},
{ set: "SOK", setName: "Saviors of Kamigawa"},
{ set: "SOM", setName: "Scars of Mirrodin"},
{ set: "SS1", setName: "Signature Spellbook: Jace"},
{ set: "STH", setName: "Stronghold"},
{ set: "SUM", setName: "Summer Magic / Edgar"},
{ set: "TBTH", setName: "Battle the Horde"},
{ set: "TD0", setName: "Magic Online Theme Decks"},
{ set: "TD2", setName: "Duel Decks: Mirrodin Pure vs. New Phyrexia"},
{ set: "TDAG", setName: "Defeat a God"},
{ set: "TFTH", setName: "Face the Hydra"},
{ set: "THP1", setName: "Theros Hero's Path"},
{ set: "THP2", setName: "Born of the Gods Hero's Path"},
{ set: "THP3", setName: "Journey into Nyx Hero's Path"},
{ set: "THS", setName: "Theros"},
{ set: "TMP", setName: "Tempest"},
{ set: "TOR", setName: "Torment"},
{ set: "TPR", setName: "Tempest Remastered"},
{ set: "TSB", setName: "Time Spiral Timeshifted"},
{ set: "TSP", setName: "Time Spiral"},
{ set: "UDS", setName: "Urza's Destiny"},
{ set: "UGIN", setName: "Ugin's Fate"},
{ set: "UGL", setName: "Unglued"},
{ set: "ULG", setName: "Urza's Legacy"},
{ set: "UMA", setName: "Ultimate Masters"},
{ set: "UNH", setName: "Unhinged"},
{ set: "USG", setName: "Urza's Saga"},
{ set: "UST", setName: "Unstable"},
{ set: "V09", setName: "From the Vault: Exiled"},
{ set: "V10", setName: "From the Vault: Relics"},
{ set: "V11", setName: "From the Vault: Legends"},
{ set: "V12", setName: "From the Vault: Realms"},
{ set: "V13", setName: "From the Vault: Twenty"},
{ set: "V14", setName: "From the Vault: Annihilation"},
{ set: "V15", setName: "From the Vault: Angels"},
{ set: "V16", setName: "From the Vault: Lore"},
{ set: "V17", setName: "From the Vault: Transform"},
{ set: "VIS", setName: "Visions"},
{ set: "VMA", setName: "Vintage Masters"},
{ set: "W16", setName: "Welcome Deck 2016"},
{ set: "W17", setName: "Welcome Deck 2017"},
{ set: "WC00", setName: "World Championship Decks 2000"},
{ set: "WC01", setName: "World Championship Decks 2001"},
{ set: "WC02", setName: "World Championship Decks 2002"},
{ set: "WC03", setName: "World Championship Decks 2003"},
{ set: "WC04", setName: "World Championship Decks 2004"},
{ set: "WC97", setName: "World Championship Decks 1997"},
{ set: "WC98", setName: "World Championship Decks 1998"},
{ set: "WC99", setName: "World Championship Decks 1999"},
{ set: "WTH", setName: "Weatherlight"},
{ set: "WWK", setName: "Worldwake"},
{ set: "XLN", setName: "Ixalan"},
{ set: "ZEN", setName: "Zendikar"}
]
